### ISSUE TITLE
can't pickle _thread.RLock objects error while running

### ISSUE THREAD

**Issue by jabirshabbir** [feferna/psoCNN#2]
Hello,
While fitting the model it throws an error "can't pickle _thread.RLock objects" at the first epoch itself.My tensorflow version is 1.10.0
This is the error traceback
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    dropout_rate=dropout)
  File "/mnt/disks/user/project/PROJECT/PSO/psoCNN.py", line 218, in __init__
    self.gBest = deepcopy(self.population.particle[i])
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/mnt/disks/user/anaconda3/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.RLock objects

**Comment by feferna** [comment]
Dear @jabirshabbir,

I think the problem may be related to the version of the Python and Tensorflow you are using. The code is not backward compatible with Tensorflow 1.10.0. It only works with at least Tensorflow 2.2.0. Try to create a new Anaconda environment using the packages with the version indicated in the README file.

Best regards.

**Comment by jabirshabbir** [comment]
Alright thank you

**Comment by love381** [comment]
I encountered the same problem, but the version used is Tensorflow 2.2.0 and the same error occurred

**Comment by feferna** [comment]
Sorry, guys. It was a bit harder to find what was going on. Apparently, it is not a good idea to deepcopy keras models and tensor. So, rewrote the code to avoid this. It should be working now.
