### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'get_default_graph' while running

### ISSUE THREAD

**Issue by jabirshabbir** [feferna/psoCNN#3]
Dear feferna,
I have updated my tensorflow to 2.2.0.
However it throws the below error
Traceback (most recent call last):
  File "main.py", line 70, in <module>
    dropout_rate=dropout)
  File "/mnt/disks/user/project/PROJECT/PSO/psoCNN.py", line 192, in __init__
    self.gBest.model_compile(dropout_rate)
  File "/mnt/disks/user/project/PROJECT/PSO/particle.py", line 147, in model_compile
    self.model = Sequential()
  File "/mnt/disks/user/anaconda3/lib/python3.7/site-packages/keras/engine/sequential.py", line 87, in __init__
    super(Sequential, self).__init__(name=name)
  File "/mnt/disks/user/anaconda3/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/mnt/disks/user/anaconda3/lib/python3.7/site-packages/keras/engine/network.py", line 96, in __init__
    self._init_subclassed_network(**kwargs)
  File "/mnt/disks/user/anaconda3/lib/python3.7/site-packages/keras/engine/network.py", line 294, in _init_subclassed_network
    self._base_init(name=name)
  File "/mnt/disks/user/anaconda3/lib/python3.7/site-packages/keras/engine/network.py", line 109, in _base_init
    name = prefix + '_' + str(K.get_uid(prefix))
  File "/mnt/disks/user/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 74, in get_uid
    graph = tf.get_default_graph()
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

My keras version is 2.2.4 Is it compatible with that?
I have tried a hack  replacing **import keras.backend** with **from  tensorflow.keras import backend** and also **from  tensorflow.python.keras import backend** either way it didnt work. Any help appreciated

**Comment by feferna** [comment]
I think it might be your Keras version. I think older Keras versions use tensorflow v1, while newer ones use tensorflow v2.

I am saying this because this error is not in my code, but somewhere in the keras code (sequential.py). Try to update Keras and see if it works.
